add User And Items controllers
culto90/java-shareit pull request #2
Opened 2022-08-12 14:28 UTC by culto90

2022-08-12 22:43 UTC, kukolev requested changes

2022-08-12 22:43 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/validations/rules/UserEmailUniqueValidationRule.java
> +    private UserStorage userStorage;
Зависимости нужно внедрять через конструктор. Использование `@Autowired` считается плохой практикой и не рекомендуется авторами Spring.

2022-08-13 11:44 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +        if (id == null) {
исправил

2022-08-13 11:46 UTC, culto90 commented on src/main/java/ru/practicum/shareit/requests/models/ItemRequest.java
> +/**
исправлено

2022-08-13 11:47 UTC, culto90 commented on src/main/java/ru/practicum/shareit/user/validations/rules/UserEmailUniqueValidationRule.java
> +    private UserStorage userStorage;
согласен, исправил.

2022-08-14 08:34 UTC, kukolev requested changes

2022-08-14 08:34 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            updatedItem.setName(item.getName());
Это присвоение названия уже не относится к валидации. Это логику уже нужно вынести в основной метод.

2022-08-14 19:32 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            updatedItem.setName(item.getName());
если все правильно понял, то исправил.

2022-08-15 07:20 UTC, kukolev approved these changes

2022-08-22 13:14 UTC, merged