add bookings
culto90/java-shareit pull request #3
Opened 2022-08-29 15:05 UTC by culto90

2022-08-30 06:20 UTC, kukolev requested changes

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controllers/BookingController.java
> +                                                                @RequestParam(required = false, defaultValue = "ALL") String state) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controllers/BookingController.java
> +                                                             @RequestParam(required = false, defaultValue = "ALL") String state) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controllers/BookingController.java
> +    public BookingDtoResponse createNewBooking(@RequestHeader(value = "X-Sharer-User-Id", required = false) Long bookerId,
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/validations/rules/BookingCheckSameDateForItemValidationRule.java
> +//@Component
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/comments/repositories/CommentRepository.java
> +    /*
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/validations/rules/CannotAddCommentWithoutReleasedBooking.java
> +            throw new ValidationException("Cannot to add Comment when user does not have any released Booking.");
Орфографическая ошибка «Can not». Нужно исправить.

Также здесь лишний предлог «to».

2022-08-30 06:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/validations/rules/CommentTextValidationRule.java
> +            throw new ValidationException("Cannot add comment to Item with nullable text.");
Орфографическая ошибка «Can not». Нужно исправить.

2022-08-30 06:31 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/controllers/BookingController.java
> +                                                                @RequestParam(required = false, defaultValue = "ALL") String state) {
исправил

2022-08-30 06:32 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/controllers/BookingController.java
> +                                                             @RequestParam(required = false, defaultValue = "ALL") String state) {
исправил

2022-08-30 06:32 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/controllers/BookingController.java
> +    public BookingDtoResponse createNewBooking(@RequestHeader(value = "X-Sharer-User-Id", required = false) Long bookerId,
исправил

2022-08-30 06:33 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/validations/rules/BookingCheckSameDateForItemValidationRule.java
> +//@Component
исправил

2022-08-30 06:33 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/validations/rules/BookingItemIsAvailableValidationRule.java
> +            throw new ItemValidationException("Cannot booking Item id = " + booking.getItem().getId() + " but it is unavailable.");
исправил

2022-08-30 06:34 UTC, culto90 commented on src/main/java/ru/practicum/shareit/comments/repositories/CommentRepository.java
> +    /*
исправил

2022-08-30 06:35 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/validations/rules/CommentTextValidationRule.java
> +            throw new ValidationException("Cannot add comment to Item with nullable text.");
исправил

2022-08-30 06:35 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/validations/rules/CannotAddCommentWithoutReleasedBooking.java
> +            throw new ValidationException("Cannot to add Comment when user does not have any released Booking.");
исправил

2022-08-30 21:35 UTC, kukolev requested changes

2022-08-31 06:58 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/entities/Item.java
> +        return getClass().hashCode();
исправил

2022-08-31 06:58 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/entities/Booking.java
> +        return getClass().hashCode();
исправил

2022-08-31 06:58 UTC, culto90 commented on src/main/java/ru/practicum/shareit/comments/entities/Comment.java
> +        return getClass().hashCode();
исправил  + в Юзере тоже

2022-08-31 20:28 UTC, kukolev requested changes

2022-08-31 20:28 UTC, kukolev commented on src/main/java/ru/practicum/shareit/utils/handlers/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleConstraintViolationException(ConstraintViolationException ex, WebRequest request) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-01 05:59 UTC, culto90 commented on src/main/java/ru/practicum/shareit/utils/handlers/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleConstraintViolationException(ConstraintViolationException ex, WebRequest request) {
исправил

2022-09-01 07:20 UTC, kukolev requested changes

2022-09-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/entities/Booking.java
> +    public int hashCode() {
Нарушение контракта equals и hashCode: "Если два объекта equals друг другу, то их хэшкоды должны быть одинаковыми. При этом если если у двух объектов одинаковые хэшкоды, то они не обязательно equals." Нарушение контракта приведет к серьезным проблемам при использовании объектов в качестве ключа в HashMap. Подробнее о проблеме и решении можно почитать тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-09-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/comments/entities/Comment.java
> +    public int hashCode() {
Нарушение контракта equals и hashCode: "Если два объекта equals друг другу, то их хэшкоды должны быть одинаковыми. При этом если если у двух объектов одинаковые хэшкоды, то они не обязательно equals." Нарушение контракта приведет к серьезным проблемам при использовании объектов в качестве ключа в HashMap. Подробнее о проблеме и решении можно почитать тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-09-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/entities/Item.java
> +    public int hashCode() {
Нарушение контракта equals и hashCode: "Если два объекта equals друг другу, то их хэшкоды должны быть одинаковыми. При этом если если у двух объектов одинаковые хэшкоды, то они не обязательно equals." Нарушение контракта приведет к серьезным проблемам при использовании объектов в качестве ключа в HashMap. Подробнее о проблеме и решении можно почитать тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-09-01 07:20 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/entities/User.java
> +    public int hashCode() {
Нарушение контракта equals и hashCode: "Если два объекта equals друг другу, то их хэшкоды должны быть одинаковыми. При этом если если у двух объектов одинаковые хэшкоды, то они не обязательно equals." Нарушение контракта приведет к серьезным проблемам при использовании объектов в качестве ключа в HashMap. Подробнее о проблеме и решении можно почитать тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-09-01 20:27 UTC, kukolev approved these changes

2022-09-23 07:25 UTC, merged