Add item requests
culto90/java-shareit pull request #4
Opened 2022-09-23 07:21 UTC by culto90

2022-09-23 18:31 UTC, kukolev requested changes

2022-09-23 18:31 UTC, kukolev commented on pom.xml
> +		<version>2.7.3</version>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-23 18:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/comment/entities/Comment.java
> +        return id.hashCode();
Поле id генерируется и значит может быть == null. В этом случает здесь будет NullPointerException. Нужно это предусмотреть.

2022-09-23 18:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/entities/Item.java
> +        return id.hashCode();
Поле id генерируется и значит может быть == null. В этом случает здесь будет NullPointerException. Нужно это предусмотреть.

2022-09-23 18:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/mappers/ItemMapper.java
> +        if (dto == null) {
По моему по логике так быть не должно. Обычно если пришел null, то и мапят его в null. Думаю это нужно поправить.

2022-09-23 18:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/entities/ItemRequest.java
> +        return id.hashCode();
Поле id генерируется и значит может быть == null. В этом случает здесь будет NullPointerException. Нужно это предусмотреть.

2022-09-23 18:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingDtoTest.java
> +    void constructorTes() {
По моему пропущена буква t в названии метода. Нужно поправить.

2022-09-24 07:34 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/mappers/ItemMapper.java
> +        if (dto == null) {
исправил

2022-09-24 07:35 UTC, culto90 commented on src/test/java/ru/practicum/shareit/booking/BookingDtoTest.java
> +    void constructorTes() {
исправлено

2022-09-24 08:19 UTC, culto90 commented on src/main/java/ru/practicum/shareit/comment/entities/Comment.java
> +        return id.hashCode();
исправил

2022-09-24 08:19 UTC, culto90 commented on src/main/java/ru/practicum/shareit/item/entities/Item.java
> +        return id.hashCode();
исправил

2022-09-24 08:20 UTC, culto90 commented on src/main/java/ru/practicum/shareit/request/entities/ItemRequest.java
> +        return id.hashCode();
исправил

2022-09-24 08:20 UTC, culto90 commented on pom.xml
> +		<version>2.7.3</version>
поменял 1 таб на 4 пробела

2022-09-24 17:23 UTC, kukolev requested changes

2022-09-24 17:23 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +                if (from == null || size == null) {
По моему вместо многократного повторения условий лучше это условие проверить один раз, а потом вызвать один из приватных методов. Примерно так:
```
if (from == null || size == null) {
    bookings = getBookingsAll(...);
} else {
    bookings = getBookingsPage(...);
}
```

Так в коде будет меньше проверок. Такой код будет проще.

Аналогично рекомендую поправить в методе getAllBookingByBookerByState

2022-09-25 07:26 UTC, culto90 commented on src/main/java/ru/practicum/shareit/booking/services/BookingServiceImpl.java
> +                if (from == null || size == null) {
исправил, так действительно код стал более локаничным и простым, спасибо

2022-09-25 17:15 UTC, kukolev approved these changes

2022-09-26 10:51 UTC, merged