Разделил монолтит на 2 модуля, добавил докер-файлы.
culto90/java-shareit pull request #5
Opened 2022-09-28 08:27 UTC by culto90

2022-09-30 11:21 UTC, kukolev requested changes

2022-09-30 11:21 UTC, kukolev commented on gateway/src/main/java/gateway/shareit/bookings/dto/BookingState.java
> +    public static boolean contains(String value) {
Код этого метода почти повторяет предыдущий. Этом метод можно упростить: 
1. вызывать from()
2. вернуть true/false в зависимости от результата в п.1

2022-09-30 11:21 UTC, kukolev commented on gateway/src/main/java/gateway/shareit/requests/controllers/ItemRequestController.java
> +                                                  @PositiveOrZero @RequestParam(required = false, defaultValue = "0") Integer from,
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-30 11:21 UTC, kukolev commented on gateway/src/main/java/gateway/shareit/requests/controllers/ItemRequestController.java
> +                                                  @Positive @RequestParam(required = false, defaultValue = "10") Integer size) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-30 11:21 UTC, kukolev commented on server/src/main/resources/application.properties
> +# Connect to DB Postgres without Docker:
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-30 11:21 UTC, kukolev commented on server/src/main/resources/application.properties
> +s#pring.datasource.username=${POSTGRES_USER}
По моему эта строчка некорректна, т.к. # после s. Это нужно поправить.

2022-09-30 15:00 UTC, culto90 commented on gateway/src/main/java/gateway/shareit/bookings/dto/BookingState.java
> +    public static boolean contains(String value) {
исправил

2022-09-30 15:01 UTC, culto90 commented on gateway/src/main/java/gateway/shareit/requests/controllers/ItemRequestController.java
> +                                                  @PositiveOrZero @RequestParam(required = false, defaultValue = "0") Integer from,
исправил

2022-09-30 15:02 UTC, culto90 commented on gateway/src/main/java/gateway/shareit/requests/controllers/ItemRequestController.java
> +                                                  @Positive @RequestParam(required = false, defaultValue = "10") Integer size) {
исправил

2022-10-01 08:14 UTC, kukolev approved these changes

2022-10-03 06:28 UTC, merged